### ISSUE TITLE
웹소켓을 이용한 채팅방 입장 및 채팅 기능 구현

### ISSUE THREAD

**Issue by SeongJongHo** [SeongJongHo/HobbyTalk-Kotlin#12]
## 💡 Feature Issue

유저가 웹소켓을 통해 채팅방에 입장하며 채팅을 주고받을 수 있는 기능을 구현합니다.

## 🌿  To-do

- [ ] 메세지 이벤트 처리 비즈니스 로직 작성
- [ ] 소켓 커넥션 종료 시 유저 상태 업데이트 및 날짜 기록 로직 작성
- [ ] 채팅 관련 application 레이어 비즈니스 로직 테스트 코드 작성
