### ISSUE TITLE
채팅룸 생성 유스케이스 작성

### ISSUE THREAD

**Issue by SeongJongHo** [SeongJongHo/HobbyTalk-Kotlin#17]
## 💡 Feature Issue

채팅룸 생성에 대한 유스케이스 작성

## 🌿  To-do

- [ ] 갯수 제한에 따른 채팅룸 생성 분산락 적용 로직 작성
- [ ] 카테고리 유효성 검사 적용 로직 작성
- [ ] 채팅방 생성시 동시에 입장 로직 작성
